resources:
  repositories:
  - repository: TestsRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: markgar
    name: markgar/CIS4Azure-Pester

trigger:
  branches:
    include:
    - master

stages:

######################################################################################
- stage: build_artifact
  displayName: Build ARM Template Artifact

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
    - checkout: TestsRepo
    - task: CopyFiles@2
      inputs:
        contents: '$(Build.SourcesDirectory)/multistage-pipeline/arm/*'
        targetFolder: $(Build.ArtifactStagingDirectory)/arm
        flattenFolders: true
    - task: CopyFiles@2
      inputs:
        contents: '$(Build.SourcesDirectory)/CIS4Azure-Pester/pester/*'
        targetFolder: $(Build.ArtifactStagingDirectory)/pester
        flattenFolders: true
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'drop'

######################################################################################
- stage: test_artifact
  displayName: Test ARM Template

  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Perform VALIDATE on the ARM template'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Mark Garner - Internal Consumption(75ebdae9-6e1c-4baa-8b2e-5576f6356a91)'
        subscriptionId: '75ebdae9-6e1c-4baa-8b2e-5576f6356a91'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'multistage-pipeline-dev'
        location: 'Central US'
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/arm/azuredeploy.json'
        csmParametersFile: '$(Build.SourcesDirectory)/arm/dev.azuredeploy.parameters.json'
        deploymentMode: 'Validate'
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '$(Build.SourcesDirectory)/packages.config'
        restoreDirectory: '$(Build.SourcesDirectory)/tests/CIS4Azure'
        feedsToUse: 'select'
        includeNuGetOrg: true
    - powershell: Install-Module Pester -Force
      displayName: 'Install Pester'
    - powershell: |
            $parameters = @{ TemplateFilePath = "$(Build.SourcesDirectory)/arm/azuredeploy.json" }
            $script = @{ Path = "tests/"; Parameters = $parameters } # runs all tests in this directory
            Invoke-Pester -Script $script -OutputFile TEST-all.xml -OutputFormat NUnitXML
      displayName: 'Run Pester Tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: '**/TEST-*.xml'
        failTaskOnFailedTests: true

######################################################################################
- stage: deploy_to_dev
  displayName: Deploy to Dev
  dependsOn: test_artifact
  condition: succeeded()

  jobs:
  - deployment: deploy_to_dev
    displayName: Deploy to Development
    environment: 'development'
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Mark Garner - Internal Consumption(75ebdae9-6e1c-4baa-8b2e-5576f6356a91)'
              subscriptionId: '75ebdae9-6e1c-4baa-8b2e-5576f6356a91'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'multistage-pipeline-dev'
              location: 'Central US'
              templateLocation: 'Linked artifact'
              csmFile: '$(pipeline.workspace)/drop/arm/azuredeploy.json'
              csmParametersFile: '$(pipeline.workspace)/drop/dev.azuredeploy.parameters.json'
              deploymentMode: 'Complete'

######################################################################################
- stage: deploy_to_test
  displayName: Deploy to Test
  dependsOn: deploy_to_dev
  condition: succeeded()

  jobs:
  - deployment: deploy_to_test
    displayName: Deploy to Test
    environment: 'test'
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Mark Garner - Internal Consumption(75ebdae9-6e1c-4baa-8b2e-5576f6356a91)'
              subscriptionId: '75ebdae9-6e1c-4baa-8b2e-5576f6356a91'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'multistage-pipeline-tst'
              location: 'Central US'
              templateLocation: 'Linked artifact'
              csmFile: '$(pipeline.workspace)/drop/arm/azuredeploy.json'
              csmParametersFile: '$(pipeline.workspace)/drop/tst.azuredeploy.parameters.json'
              deploymentMode: 'Complete'
          