trigger:
  branches:
    include:
    - master
  
stages:

######################################################################################
- stage: build_artifact
  displayName: Build Artifact

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/arm' 
        artifactName: 'drop'

######################################################################################
- stage: test_artifact
  displayName: Test Artifact

  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: drop
    - script: Invoke-Pester
      displayName: 'Run a one-line script'

######################################################################################
- stage: deploy_to_dev
  displayName: Deploy to Dev
  dependsOn: test_artifact
  condition: succeeded()

  jobs:
  - deployment: deploy_to_dev
    displayName: Deploy to Development
    environment: 'development'
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:

          steps:
          - script: echo Deploy to Dev here!
            displayName: 'Run a one-line script'

######################################################################################
- stage: deploy_to_test
  displayName: Deploy to Test
  dependsOn: deploy_to_dev
  condition: succeeded()

  jobs:
  - deployment: deploy_to_test
    displayName: Test
    environment: 'test'
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:

          steps:
          - script: echo Deploy to Test here!
            displayName: 'Run a one-line script'
          